# Generated by Django 4.1.7 on 2023-05-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlmoodle', '0004_event_forum_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
