# Generated by Django 4.2 on 2023-05-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlmoodle', '0005_uploadedfile'),
        ('atlmoodle', '0006_remove_forum_name_forum_user'),
    ]

    operations = [
    ]
