# Generated by Django 4.2 on 2023-05-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlmoodle', '0007_merge_20230513_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
