# Generated by Django 4.1.7 on 2023-05-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlmoodle', '0007_remove_tutor_user'),
        ('atlmoodle', '0009_uploadedfile'),
    ]

    operations = [
    ]
