# Generated by Django 4.2 on 2023-05-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlmoodle', '0010_merge_0007_remove_tutor_user_0009_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('testes', 'Testes'), ('visitas', 'Visitas de Estudo'), ('feriados', 'Feriados'), ('greves', 'Greves'), ('ferias', 'Férias')], default='testes', max_length=20),
        ),
    ]
