# Generated by Django 4.1.7 on 2023-05-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlmoodle', '0010_merge_0007_remove_tutor_user_0009_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='forum',
            name='user',
            field=models.CharField(default='', max_length=300),
        ),
    ]
