# Generated by Django 4.1.7 on 2023-05-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlmoodle', '0011_discussion_user_alter_forum_user'),
    ]

    operations = [
    ]
