# Generated by Django 4.2 on 2023-05-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlmoodle', '0014_uploadedfile_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='aluno',
            name='first_name',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='aluno',
            name='last_name',
            field=models.CharField(default='', max_length=240),
        ),
    ]
