# Generated by Django 4.2 on 2023-05-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlmoodle', '0015_aluno_email_aluno_first_name_aluno_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('testes', 'Testes'), ('visitas', 'Visitas de Estudo'), ('feriados', 'Feriados'), ('greves', 'Greves'), ('ferias', 'Férias')], default='testes', max_length=20),
        ),
    ]
